BurntSushi/quickcheck

- src/arbitrary.rs
- src/tester.rs
Fix for current rust nightly, I've renamed:
* `TaskRng` to `ThreadRng`
* `task_rng` to `thread_rng`
See: https://github.com/rust-lang/rust/commit/1e89bbcb67020892bc0af5af218c35f0fd453fa4
> TaskRng -> ThreadRng, task_rng -> thread_rng

- examples/out_of_bounds.rs
- examples/reverse.rs
- examples/reverse_single.rs
- examples/sieve.rs
- examples/sort.rs
- quickcheck_macros/examples/attribute.rs
- quickcheck_macros/src/lib.rs
- quickcheck_macros/tests/macro.rs
- src/arbitrary.rs
- src/lib.rs
- src/tester.rs
- src/tests.rs
- uint/int -> usize/isize
- `box foo` -> `Box::new(foo)`
- `hash` module and `String/Show` fallout
- added `#[allow(unstable)]` and `#[feature(int_uint)]` to avoid a flood of warnings (but you may want to audit their use in a follow up commit)
> update to rust nightly

- src/arbitrary.rs
Fixes the following compile error with latest Rust nightly:
```
~/src/rust-quickcheck[master] $ rustc --version
rustc 1.0.0-nightly (706be5ba1 2015-02-05 23:14:28 +0000)
~/src/rust-quickcheck[(0.1.37)] $ cargo test
Compiling quickcheck v0.1.37 (file:///home/caspar/src/rust-quickcheck)
src/arbitrary.rs:390:20: 390:27 error: obsolete syntax: `:`, `&mut:`, or `&:` syntax
src/arbitrary.rs:390         let cat = |&mut: x: &Vec<A>| {
^~~~~~~
note: rely on inference instead
src/arbitrary.rs:390:20: 390:27 error: obsolete syntax: `:`, `&mut:`, or `&:` syntax
src/arbitrary.rs:390         let cat = |&mut: x: &Vec<A>| {
^~~~~~~
note: rely on inference instead
error: aborting due to previous error
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile …
```
> Fix Rust nightly compile error by relying on closure type inference instead of type annotation

- README.md
- examples/sieve.rs
This PR extends the sieve example to advocate constructing properties that are as strict as possible. Currently the `prop_all_prime` only tests that the numbers returned by the sieve are all prime but it doesn't ensure the list is complete. I thus extended `README.md` with another property that tests the sieve for equivalence with a naive primality test.
> Extend the sieve example slightly

- examples/out_of_bounds.rs
- src/arbitrary.rs
I didn't replace the uses of the deprecated `range_step` because that function's misuse is the point of the tests that use it. However, as it will be removed eventually, we should find a better example.
> update to Rust master

- src/tester.rs
- src/tests.rs
It is sufficient to constrain the error type to be `Debug + Send + 'static` instead of limiting it to `String` only.
> Implement Testable for more generic results

- src/tester.rs
- src/tests.rs
This allows for some useful patterns, such as
- testing functions without a return value that only fail by panicking,
- testing functions that return a `Result<(), ...>` that only fail by returning an error.
(This is based on top of #79.)
> Implement Testable for ()

- quickcheck_macros/src/lib.rs
ItemFn changed, with this it builds again.
The second commit updates from Modifier to MultiModifer, the former is deprecated.
> Update for rust changes as of 7cb9914fc 2015-05-25

- README.md
When adding the quickcheck dependencies only for dev mode, the plugin also has to be loaded only for testing.
Otherwise the compiler complains about missing dependency of quickcheck_macros.
> Update README, enable plugin only for testbuild

- Cargo.toml
- src/lib.rs
- src/tester.rs
Debug macros are only used in one place, so logger initialization can simply happen there.
Fixes #95.
> Use `env_logger` to support `RUST_LOG` again

- src/arbitrary.rs
The `empty` iterator is a zero sized type, and this way the empty
shrinker (also the default shrinker) uses no allocation at all.
empty and once require Rust 1.2 or later.
> Use std::iter::empty inside empty_shrinker

- quickcheck_macros/src/lib.rs
As of https://github.com/rust-lang/rust/pull/30043, `rustc::plugin` is
now `rustc_plugin`.
> Fix the travis build on nightly

- Cargo.toml
- src/arbitrary.rs
- src/lib.rs
Arbitrary SystemTime can only be generated when built with `--features
unstable`. It doesn't seem like new arbitrary implementaions normally
get tested, so I've not added any tests for these. I also can't think of
any particularly important values for `shrink` here, as no durations or
times are particularly more likely to cause bugs than others.
We're moduloing the number of nanoseconds for a duration to always be
subsecond, so we don't get any isses when seconds is generated to
`u64::MAX_VAL`, or close to it.
Fixes #109.
> Add support for std::time::{Duration, SystemTime}

- quickcheck_macros/src/lib.rs
This initializer was moved into a method in https://github.com/rust-lang/rust/commit/ec8ea22c7f59fd898670060bceb6810cef68ca0a.
> Fixed regression in nightly

- src/arbitrary.rs
> Bias generated `char`s (#99)

- src/tester.rs
- src/tests.rs
Fix showing the message after panic from panic!() or assert!()
Typical panics produce either &str or String (depending if formatting is
used or not), so we use a simple type switch to handle these two after
a panic in a test case.
Fixes #91
> Fix showing the message after panic from panic!() or assert!()

- src/arbitrary.rs
- src/tester.rs
- src/tests.rs
For information, here is the [log before and after](https://gist.github.com/mcarton/e63f21992e18a0ade18d) with Clippy.
The remaining warning can be considered a false positive here.
> Cleanup some warnings from Clippy

- src/tester.rs
Re: tickets #126 and #127.
This ensures that we try to recursively shrink a failing case, in order to find the smallest instance. Repeating myself, this means that the test case:
```rust
#[cfg(test)]
mod test {
use quickcheck::quickcheck;
#[test]
fn testy_test() {
use quickcheck::Arbitrary;
fn thetest(vals: Vec<bool>) -> bool {
vals.iter().filter(|&v| *v).count() < 2
}
quickcheck(thetest as fn(vals: Vec<bool>) -> bool)
}
```
Will fail with `[quickcheck] TEST FAILED. Arguments: ([true, true])`, rather than something like `[quickcheck] TEST FAILED. Arguments: ([false, false, false, true, true, true, false, true, true, ...])`. This was mostly just adapting the logic used previously to the new macro.
I'd welcome any feedback on how you think it might be improved.
Thanks,
> Port over the shrinking behavior from before f017c01.

- src/arbitrary.rs
- src/lib.rs
`duration_from_earlier` was renamed to `duration_since`, and the time2
feature is no longer needed. This can be removed from the unstable
feature gate once 1.8 is released, but these changes are required to
compile on beta and nightly.
> time2 has been stabilized

- Cargo.toml
- README.md
- src/lib.rs
- src/tester.rs
This is to allow a faster compile of quickcheck. Logging brings a lot of dependencies that are more or less unused.
Fixes #142
> Add crate feature "use_logging" that's enabled by default

- quickcheck_macros/src/lib.rs
Fixes #149.
Looks like this wrapper around `cx.item_fn` was added in https://github.com/BurntSushi/quickcheck/commit/60754695aa9a944bd73e58752630c2eaaf81a06e due to a bug in Rust which was later fixed in Jan 2015: https://github.com/rust-lang/rust/pull/21504.
> Fix for `rustc 1.14.0-nightly (f09420685 2016-10-20)`.

- src/tester.rs
In practice I've wanted two kinds of quickcheck runs: fast and
comprehensive. To date the comprehensive testing has been done
by manually adjusting tests / max_tests up from the defaults of
100 / 10000. This involves a recompilation step.
If quickcheck were able to read environment variables to set its
tests / max_tests that recompilation step would not be needed and
a nightly CI task could be written to do a comprehensive QC run.
This commit introduces QC_TESTS and QC_MAX_TESTS to meet the
above. In the event that QC_MAX_TESTS < QC_TESTS then the
max_tests will be set to QC_TESTS.
Signed-off-by: Brian L. Troutwine blt@postmates.com
> Allow QC_TESTS and QC_MAX_TESTS to set tests / max_tests

- src/lib.rs
- src/tests.rs
I wanted to be able to `#[ignore]` some of my quickcheck tests defined with `quickcheck!` because they're expensive and I don't want to run them every time in dev. This (short) PR adds that ability.
I *don't* have tests for this, because I wasn't sure how to go about doing so. All existing tests pass, however.
quickcheck! {
#[ignore]
fn prop(...) -> bool {
...
}
}
> Added attr support to quickcheck! macro.

- .travis.yml
- quickcheck_macros/Cargo.toml
- quickcheck_macros/src/lib.rs
[“Clean up `ast::Attribute`, `ast::CrateConfig`, and string interning”](https://github.com/rust-lang/rust/pull/37824)
Resolves these errors:
```
error[E0425]: unresolved name `token::intern`
--> src/lib.rs:27:35
|
27 |     reg.register_syntax_extension(token::intern("quickcheck"),
|                                   ^^^^^^^^^^^^^ unresolved name
error[E0425]: unresolved name `token::str_to_ident`
--> src/lib.rs:86:23
|
86 |     let check_ident = token::str_to_ident("quickcheck");
|                       ^^^^^^^^^^^^^^^^^^^ unresolved name
error[E0425]: unresolved name `token::intern_and_get_ident`
--> src/lib.rs:107:34
|
107 |         span, cx.meta_word(span, token::intern_and_get_ident("test"))));
|                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^ unresolved name
error: …
```
> quickcheck_macros: Update for rust-lang/rust#37824

- src/arbitrary.rs
Lots of boilerplate is required when implementing `Arbitrary` for recursive types.
Having an impl of `Arbitrary` for boxes would be quite nice when working with such structures!
> Implement `Arbitrary` for `Box`

- quickcheck_macros/src/lib.rs
e.g.
```
#[quickcheck] fn test(mut xv: Vec<i32>) {}
```
fails with E0561
> unbreak attribute for functions with pattern parametres

- src/arbitrary.rs
- src/tests.rs
The motivation for this is that I want to use a non-standard hasher (in my case, [fnv](https://doc.servo.org/fnv/)) instead of the default `SipHasher`. However, the current implementation has trait bounds that implicitly restrict the third parameter of `HashMap` (or second of `HashSet`) to the [default](https://doc.rust-lang.org/std/collections/hash_map/struct.RandomState.html).
It turned out to be very simple to address this: parameterizing the `impl`'s with the hasher type parameter `S` works with both the short-hand generally used (`HashMap<K, V>` or `HashSet<K>`) and with types that have the third specified (e.g. `HashMap<K, V, BuildHasherDefault<FnvHasher>>`).
The added tests are purely compilation tests: if they compile, they pass. One set checks that the normal `HashMap<K, V>` …
> Add Arbitrary for non-default Hashers in HashMap/HashSet

- src/arbitrary.rs
- src/tester.rs
Previously, certain generator sizes would wrap, calling gen_range with
invalid ranges, causing assertion errors.
This is a little tricky because isize::min_value().abs() overflows.
Fixes #143.
> Take type bounds into account in integer Arbitrary

- benches/tuples.rs
- src/arbitrary.rs
This implementation relies less on cloning while shrinking, which is a performance boost, evident from benchmarks:
```
name                   before ns/iter  after ns/iter  diff ns/iter   diff %  speedup 
shrink_f64_1_tuple     607             607                       0    0.00%   x 1.00 
shrink_f64_2_tuple     1,099           1,019                   -80   -7.28%   x 1.08 
shrink_f64_3_tuple     1,932           1,657                  -275  -14.23%   x 1.17 
shrink_f64_4_tuple     2,925           2,448                  -477  -16.31%   x 1.19 
shrink_f64_5_tuple     4,041           3,368                  -673  -16.65%   x 1.20 
shrink_f64_6_tuple     5,989           4,790                -1,199  -20.02%   x 1.25 
shrink_f64_7_tuple     8,524           6,207                -2,317  -27.18% …
```
> Rewrite `impl Arbitrary for tuples` macros

- README.md
The proptest crate is well documented and provides a fresh take on
property based testing inspired by the Hypothesis framework for Python.
In particular, it appears to improve the shrinking story that can be
inconvenient to work with in QuickCheck.
See also: https://github.com/AltSysrq/proptest/issues/15
cc @AltSysrq --- Does the wording look OK to you? Any suggestions?
> readme: add link to proptest crate

- Cargo.toml
Just a version bump
Can you release new version of quickcheck to crates.io?
> Update rand to version 0.4

- Cargo.toml
- README.md
- src/arbitrary.rs
- src/lib.rs
Now that rust-lang-nursery/rand#163 is merged we can do this.
Closes #162.
> Implement Arbitrary for 128-bit integers

- quickcheck_macros/src/lib.rs
This fixes changes introduced in this commit https://github.com/rust-lang/rust/commit/56e8f29dbe89f2109cacc8eb5e92ea3de32eefb9
> fix nightly, match header in ItemKind::Fn

- quickcheck_macros/src/lib.rs
This fixes #212, introduced in rust-lang/rust@82607d2cf3866c7cc31050548f2fbfa39207e319.
> fix nightly, rename codemap to source_map

- .travis.yml
- Cargo.toml
- benches/tuples.rs
- src/arbitrary.rs
This PR updates `rand` crate to version 0.5.
Minimum Rust version (in .travis.yml) pushed to 1.22.0.
> Update rand crate to 0.5

- README.md
Changes the build badge to point to the latest build result of master. Currently it will show the latest completed build status, regardless of branch.
URL recommended by Travis, as show [here](https://i.imgur.com/KnIKbNJ.png).
> Fix failing build badge

- .travis.yml
- quickcheck_macros/Cargo.toml
- quickcheck_macros/examples/attribute.rs
- quickcheck_macros/src/lib.rs
- quickcheck_macros/tests/macro.rs
This makes `quickcheck_macros` usable on stable since Rust 1.30, but is a breaking change.
> macros: switch to using `proc-macro`

- README.md
Rust 1.30 added support for attribute-like procedural macros, so Rust nightly is no longer necessary to use the `quickcheck` attribute macro in the `quickcheck_macros` crate.
> Update README for procedural macros in Rust 1.30

- src/lib.rs
This makes possible using the macro as `quickcheck::quickcheck!` without `use quickcheck::quickcheck;` in Rust 2018.
> Use `$crate::` prefix in `quickcheck!`

- .travis.yml
- Cargo.toml
- src/tester.rs
This requires bumping minimum supported Rust version to 1.32.0 due to [getrandom](https://github.com/rust-random/getrandom) crate.
> Update to rand 0.7 and rand_core 0.5

- quickcheck_macros/Cargo.toml
- quickcheck_macros/src/lib.rs
Updated the version specifiers in `Cargo.toml` of `quickcheck_macros` and fixed the compiler errors.
I don't have any experience with `syn` and was following the docs and compiler errors. I think I got it right.
> Upgrade syn, quote, and proc-macro2 deps to 1.0

- src/arbitrary.rs
`Gen::size()` (really, the `size` parameter) is described in the docs for StdGen and StdThreadGen, but not in the docs for Gen. So, I copied and pasted the description to the docs for Gen.
I considered moving the paragraph to Gen's docs outright and having StdGen & StdThreadGen link to the new location, but I couldn't find a way to link directly to the `size` function (and the point of this PR is to reduce how much users need to hunt around, anyway).
I also considered linking "default size" in QuickCheck::new to the new documentation in Gen::size because it might be unclear what that means, but the house style of the docs seems to recommend not including internal links (maybe waiting for intra-rustdoc links?), so I didn't add any.
> Document Gen::size

- src/arbitrary.rs
- src/tester.rs
See #268. This ensures that the shrinker does not panic when _using_ the value, not just _constructing_ it.
> Eliminate panic on overflowing absolute value

- src/arbitrary.rs
- src/tester.rs
Like a few other macros, `panic!` accepts a format string and arguments.
The format string is meant to be static and calling it with a message string will generate a warning.
Currently, the warning also indicates that `rustc` will generate an error instead in the near future.
> Shut up non_fmt_panic warning

- src/arbitrary.rs
Uses [`std::array::from_fn`](https://doc.rust-lang.org/stable/std/array/fn.from_fn.html), which was introduced in [Rust 1.63.0](https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html#stabilized-apis), ~1 year ago
> feat: support arbitrary arrays

- src/lib.rs
Currently https://docs.rs/quickcheck doesn't say much about what this crate does. I think having most info in the README is OK, but probably there should be some info in the crate docs root as well.
> Explain what the crate does in lib.rs docs

- src/tester.rs
fixes #303 
This cuts my prop test run-times nearly in half!
Here's the new flamegraph showing nearly 70% of time spent in test, previously this was 40%.
compare to prior run:
> Only build debug representations of arguments on failing tests
